#ifndef VERSION_H
#define VERSION_H

#define KERNEL_NAME     "air"
#define KERNEL_VERSION  "0.1.0"
#define KERNEL_COMMIT   "fc0814e"
#define KERNEL_DIRTY    1
#define KERNEL_BUILD_TS "Aug 31 2025 20:41:13"
#define KERNEL_ARCH     "x86_64"

#if KERNEL_DIRTY
#define KERNEL_VERSION_STRING KERNEL_NAME " " KERNEL_VERSION " " KERNEL_COMMIT "-dirty " KERNEL_BUILD_TS " " KERNEL_ARCH
#else
#define KERNEL_VERSION_STRING KERNEL_NAME " " KERNEL_VERSION " " KERNEL_COMMIT " " KERNEL_BUILD_TS " " KERNEL_ARCH
#endif

#endif
